package com.example.springbootdemo.dto;

import java.math.BigDecimal;
import java.util.Date;

public class FacBuyer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer.avatarUrl
     *
     * @mbggenerated
     */
    private String avatarurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer.balance
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer.points
     *
     * @mbggenerated
     */
    private Short points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer.registry_time
     *
     * @mbggenerated
     */
    private Date registryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer.operator_id
     *
     * @mbggenerated
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer.operator_name
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fac_buyer.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer.id
     *
     * @return the value of fac_buyer.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer.id
     *
     * @param id the value for fac_buyer.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer.nick_name
     *
     * @return the value of fac_buyer.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer.nick_name
     *
     * @param nickName the value for fac_buyer.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer.name
     *
     * @return the value of fac_buyer.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer.name
     *
     * @param name the value for fac_buyer.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer.token
     *
     * @return the value of fac_buyer.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer.token
     *
     * @param token the value for fac_buyer.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer.open_id
     *
     * @return the value of fac_buyer.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer.open_id
     *
     * @param openId the value for fac_buyer.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer.gender
     *
     * @return the value of fac_buyer.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer.gender
     *
     * @param gender the value for fac_buyer.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer.avatarUrl
     *
     * @return the value of fac_buyer.avatarUrl
     *
     * @mbggenerated
     */
    public String getAvatarurl() {
        return avatarurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer.avatarUrl
     *
     * @param avatarurl the value for fac_buyer.avatarUrl
     *
     * @mbggenerated
     */
    public void setAvatarurl(String avatarurl) {
        this.avatarurl = avatarurl == null ? null : avatarurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer.balance
     *
     * @return the value of fac_buyer.balance
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer.balance
     *
     * @param balance the value for fac_buyer.balance
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer.points
     *
     * @return the value of fac_buyer.points
     *
     * @mbggenerated
     */
    public Short getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer.points
     *
     * @param points the value for fac_buyer.points
     *
     * @mbggenerated
     */
    public void setPoints(Short points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer.registry_time
     *
     * @return the value of fac_buyer.registry_time
     *
     * @mbggenerated
     */
    public Date getRegistryTime() {
        return registryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer.registry_time
     *
     * @param registryTime the value for fac_buyer.registry_time
     *
     * @mbggenerated
     */
    public void setRegistryTime(Date registryTime) {
        this.registryTime = registryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer.create_time
     *
     * @return the value of fac_buyer.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer.create_time
     *
     * @param createTime the value for fac_buyer.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer.update_time
     *
     * @return the value of fac_buyer.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer.update_time
     *
     * @param updateTime the value for fac_buyer.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer.operator_id
     *
     * @return the value of fac_buyer.operator_id
     *
     * @mbggenerated
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer.operator_id
     *
     * @param operatorId the value for fac_buyer.operator_id
     *
     * @mbggenerated
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer.operator_name
     *
     * @return the value of fac_buyer.operator_name
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer.operator_name
     *
     * @param operatorName the value for fac_buyer.operator_name
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fac_buyer.is_deleted
     *
     * @return the value of fac_buyer.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fac_buyer.is_deleted
     *
     * @param isDeleted the value for fac_buyer.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}